DROP TABLE PAYMENT;
CREATE TABLE PAYMENT(
  PAYMENTNO VARCHAR2(30),
  USERID VARCHAR2(15),
  PRODUCTNO NUMBER,  
  PRICE VARCHAR2(15),
   contact VARCHAR2(13),
  PRODUCTNAME VARCHAR2(30 CHAR),
  PAYMENTFILE VARCHAR2 (50 CHAR),
  REGDATE DATE, 
  CONSTRAINT payment_NO_PK PRIMARY KEY(paymentNO)
);

 CREATE TABLE BASKET 
   (	
    BASKETNO NUMBER, 
	USERID VARCHAR2(50 CHAR), 
    SHIPNO NUMBER,
	PRODUCTNAME VARCHAR2(20 CHAR), 
	PRICE VARCHAR2(20 CHAR), 
	BASKETFILE VARCHAR2(50 CHAR),
    REGDATE DATE,
	CONSTRAINT BASKET_NO_PK PRIMARY KEY(BASKETNO)
   );

CREATE SEQUENCE payment_seq
  MINVALUE 1
  MAXVALUE 9999999
  INCREMENT BY 1
  START WITH 1;
  COMMIT;
 
 select TO_CHAR(REGDATE, 'YYYY-mm-DD') from payment;